# Generated by Django 3.1.5 on 2021-01-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20210115_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgFileName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
