# Generated by Django 3.1.5 on 2021-01-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_post_imgfilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgFileName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
