# Generated by Django 3.1.5 on 2021-01-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20210120_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imgFileName',
        ),
        migrations.AddField(
            model_name='post',
            name='img_file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
